### ISSUE TITLE
Releasing and Packaging

### ISSUE THREAD

**Issue by ruffsl** [ros2-rust/ros2_rust#9]
A big part in making Rust more attractive for ROS2 community and vice versa would be in providing released packages, making rclrs (or portions of) more readable installable. As may ROS users may be unfamiliar with Rust, given ROS's legacy with C++ and Python, simplifying installation could help lower the barrier and learning curve. Ideally, it would be nice to see rclrs as easy to include as an external crate, just as relying upon any other package released on crates.io , but I'd also be happy if debians could be shipped via synced ROS2 releases.

**Comment by nnmm** [comment]
I think this can be closed now since `rclrs` is available on crates.io.

There is also discussion about adding it to the core ROS 2 distribution, but that's probably better tracked elsewhere (REPs or so) than here: https://discourse.ros.org/t/process-for-third-party-client-libraries-to-be-incorporated-into-the-core-ros-2-distribution/27325/23
